/*
 * This source file was generated by the Gradle 'init' task
 */
package com.app;

import com.app.command.FileOrganizerCommand;
import picocli.CommandLine;

/** Main application class for the File Organizer CLI. */
public class App {
  /**
   * Main entry point of the application.
   *
   * @param args Command line arguments passed to the application
   */
  public static void main(String[] args) {
    int exitCode = new CommandLine(new FileOrganizerCommand()).execute(args);
    System.exit(exitCode);
  }
}
